### ISSUE TITLE
The type initializer for 'log4net.Core.LoggerManager' threw an exception.  in "MTApiService"

### ISSUE THREAD

**Issue by Calx-Takeno** [vdemydiuk/mtapi#163]
at log4net.Core.LoggerManager.GetRepository(Assembly repositoryAssembly)
   at log4net.LogManager.GetRepository()
   at MTApiService.LogConfigurator.Setup(String profileName)
   at MtApi5.MtApi5Client..ctor()
   at Forex.Services.QueryService..ctor() in D:\Calx\Forex.EA\Forex.Services\QueryService.cs:line 19
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate() in C:\projects\autofac\src\Autofac\Core\Activators\Reflection\ConstructorParameterBinding.cs:line 127

**Comment by vdemydiuk** [comment]
Can you try to run test application to reproduce the same issue? 
I can't reproduce it in my environment.

**Comment by Calx-Takeno** [comment]
It appears on .NET Core 2.2 environment.
I try it in .NET Framework 4.6.1. It works well.
Could mtapi support .NET Core 2.0+ Or .NET Stand 2.0?
I have some AI libraries and ML libraries base on .NET CORE.

**Comment by vdemydiuk** [comment]
I think it's impossible. I have used WCF as communication core and it requires .NET 4+.
