### ISSUE TITLE
Errors on parsing JSON

### ISSUE THREAD

**Issue by sergshu** [vdemydiuk/mtapi#45]
I've got an error on backtesting on MT4:
{"After parsing a value an unexpected character was encountered: \". Path 'Orders[0]', line 1, position 201."}
Stack Trace:
...
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at MtApi.MtApiClient.SendRequest[T](RequestBase request) in C:\Users\Serg\Source\Repos\mtapi\MtApi\MtApiClient.cs:line 2365
   at MtApi.MtApiClient.GetOrders(OrderSelectSource pool) in C:\Users\Serg\Source\Repos\mtapi\MtApi\MtApiClient.cs:line 505
   at MtApi.Monitors.TradeMonitor.CheckOrders() in C:\Users\Serg\Source\Repos\mtapi\MtApi\Monitors\TradeMonitor.cs:line 102
   at MtApi.Monitors.TradeMonitor.Check() in C:\Users\Serg\Source\Repos\mtapi\MtApi\Monitors\TradeMonitor.cs:line 82
   at MtApi.Monitors.TimeframeTradeMonitor.ApiClient_OnLastTimeBar(Object sender, TimeBarArgs e) in C:\Users\Serg\Source\Repos\mtapi\MtApi\Monitors\TimeframeTradeMonitor.cs:line 51
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at MtApi.MtApiClient.FireOnLastTimeBar(MtTimeBar timeBar) in C:\Users\Serg\Source\Repos\mtapi\MtApi\MtApiClient.cs:line 2421
   at MtApi.MtApiClient._client_MtEventReceived(MtEvent e) in C:\Users\Serg\Source\Repos\mtapi\MtApi\MtApiClient.cs:line 2411
   at MTApiService.MtClient.OnMtEvent(MtEvent e) in C:\Users\Serg\Source\Repos\mtapi\MTApiService\MtClient.cs:line 250
   at SyncInvokeOnMtEvent(Object , Object[] , Object[] )
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)

Parsing string:
{"Orders" : [{"MagicNumber" : 262,"MtCloseTime" : 0,"Commission" : "0","Symbol" : "EURUSD","StopLoss" : 1.116,"OpenPrice" : 1.11934,"MtOpenTime" : 1475608025,"Comment" : "","Magic":262,"RequestType":3},"Ticket" : 1,"Lots" : 1,"ClosePrice" : 1.1192,"Profit" : -14,"TakeProfit" : 1.12747,"Swap" : 0,"MtExpiration" : 0,"Operation" : 0}],"ErrorCode" : 0}

**Comment by PierrePavageau** [comment]
Hi. Same issue here, calling the GetOrders method (MQL4).
Error : After parsing a value an unexpected character was encountered: ". Path 'Orders[0]', line 1, position 201.
Data :
{"Orders" : [{"MagicNumber" : 887,"MtCloseTime" : 0,"Commission" : "0","Symbol" : "GER30","StopLoss" : 11635,"OpenPrice" : 11653.95,"MtOpenTime" : 1485968741,"Comment" : "","Magic":887,"RequestType":3}","Ticket" : 112

Seems like the closing "]" is missing.

**Comment by vdemydiuk** [comment]
I have found that problem is related to order Comment that Exptert is trying to get in test mode during call function GetOrder/GetOrders from history pool. MetaTrader can return wrong comment string  like this: ","Magic":372,"RequestType"[tp] .This string has broken json that is using in response of functions GetOrder/GetOrders.
I will disable using comment of order in backtesting mode. Unfortunately, this is only solution to fix this problem.
